const dataInfo = [
  
   {
    id: 0,
    image: "/images/women shirt.jpg",
    title: "Women's shirt",
    description: "Elegant  casual shirt",
    productLink:"https://onelink.shein.com/41/5up4ss2t34vt",
  },
  {
    id: 1,
    image: "/images/women dress 1.jpg",
    title: " Women's Spring Elegant Vintage Floral Print Belted Long Dress",
    description: "Vuslat Women's Spring Elegant Vintage Floral Print Belted Long Dress - Beige Gold Flower 3/4 Sleeve Pleated Dress With Pockets, Suitable For Garden, Commute, Photoshoot, Tea Party, Valentine's Day, ",
     productLink:"https://onelink.shein.com/41/5up3xrbbuc95",

  },
  {
    id: 2,
    image: "/images/women dress 2.jpg",
    title: "Elegant Halter Neck Dress",
    description: "Franclia Women's Elegant Halter Neck Dress,Golden Yellow Summer Tropical Cocktail Blazer Collar Metal Decor Waist Cinching Short Minimalist Slouchy Dress",
     productLink:"https://onelink.shein.com/41/5up4ci2n53l0",

  },
   {
    id: 3,
    image: "/images/women dress 3.jpg ",
    title: "Women's Sleeveless A-Line Mini Dress",
    description: "Women's Sleeveless A-Line Mini Dress, Contrast Stripe Print Round Neck Zipper Back, Casual Elegant For Vacation, Party, Beach, Daily, Spring Summer",
     productLink:"https://onelink.shein.com/40/5ueha3c4ewjf",

  },
 
  {
    id: 4,
    image: "/images/women dress 4.jpg",
    title: "Sexy Knit Cut Out Circle Decoration Slim Beach Mini Dress 2026",
    description: "Sexy Knit Cut Out Circle Decoration Slim Beach Mini Dress 2026 Women's Cover Ups Vacation Chic Seaside Beachwear Swimsuit Cover Up Tunic Party Dresses 200+ sold",
     productLink:"https://onelink.shein.com/40/5uegu946h00o",
  },
{
    id: 5,
    image: "/images/women dress 5.jpg",
    title: "Bohemian Style Backless Maxi Dress, Suitable For Beach, Vacation And Coastal Travel",
    description: "Bohemian Style Backless Maxi Dress, Suitable For Beach, Vacation And Coastal Travel.",
     productLink:"https://onelink.shein.com/40/5uegdp8ugfid",
  },
  {
    id: 6,
    image: "/images/women dress 6.jpg",
    title: "Sunnyshic Women's White Summer Casual Holiday Vacation,Bohemian Tropical Wear,Crochet Shell Tassel",
    description: "Sunnyshic Women's White Summer Casual Holiday Vacation Cropped Camisole Dress,Star & Moon Decor,Backless Bohemian Tropical Resort Wear,Crochet Shell Tassel",
     productLink:"https://onelink.shein.com/39/5tp1csf7ox0q",
  },
   {
    id: 7,
    image: "/images/women dress 7.jpg ",
    title: "Summer New Elegant Exquisite Sequin Embroidered Puff Sleeve dress",
    description: "summer outfit .,Simplee Women's Summer New Elegant Exquisite Sequin Embroidered Puff Sleeve High Waist A-Line Short Dress, Stand Collar Design, Lace Patchwork, Suitable For Wedding Party, Birthday Party, Dating, Outing, Vacation, Graduation Season.",
     productLink:"https://onelink.shein.com/39/5t347vo7miwl",
  },
 
  {
    id: 8,
    image: "/images/women dress 8.jpg",
    title: "Women's Summer New Y2K Style Yellow 2-Piece Set, Lightweight Knit Cropped Top Paired",
    description: "Women's Summer New Y2K Style Yellow 2-Piece Set, Lightweight Knit Cropped Top Paired With High-Waisted Bodycon Pencil Skirt, Boho Style, Suitable For Beach Vacation, Travel, Date, Beach Party, Pool Party, Graduation Ceremony And Cocktail Party 50+ sold",
     productLink:"https://onelink.shein.com/35/5qcdwzoeszf6",
  },

{
    id: 9,
    image: "/images/women dress 9.jpg",
    title: "Sleeveless Sweater Vest, Versatile Knit Waistcoat Summer",
    description: "Solid Color Short Round Neck Asymmetrical Button Accessory Design Fashion Sleeveless Sweater Vest, Versatile Knit Waistcoat Summer 200+ sold",
     productLink:"https://onelink.shein.com/35/5qcd3o2vhir3",
  },
  {
    id: 10,
    image: "/images/women dress 10.jpg",
    title: "bandana",
    description: "Hand Crocheted Hollow Hair Scarf – Lobster Stripes & Floral Hollow Tassel Triangle Bandana, Summer/Beach/Festival Hairstyle Accessory,Holiday,Travel Summer Headbands Beach Hair Bands,Party,Birthday 🎁60% OFF COUPON for every New User",
     productLink:"https://onelink.shein.com/35/5qce5bl3uija",
  },
   {
    id: 11,
    image: "/images/women dress 11.jpg ",
    title: "Summer Elegant Commuter Casual Apricot Base Leaf Print Sleeveless Halter Neck Bow Tie Neckline",
    description: "Elenzga Women's Summer Elegant Commuter Casual Apricot Base Leaf Print Sleeveless Halter Neck Bow Tie Neckline Wooden Bead Decor Asymmetric Hem Waist Criss-Cross Tie Fitted Slim Waist Flattering Tank Top 900+ sold 🎁60% OFF COUPON for every New User!.",
     productLink:"https://onelink.shein.com/7/5powhiale2b5",
  },
 
  {
    id: 12,
    image: "/images/women dress 12.jpg",
    title: "Sexy Business Casual Cross Front Halter Wide Leg Jumpsuit For Women",
    description: "Hauture Old Money Sexy Business Casual Cross Front Halter Wide Leg Jumpsuit For Women – Elegant White Minimalist Evening Romper, Chic Formal Office Party Outfit, Statement Professional Workwear 🎁60% OFF COUPON for every New User!.",
     productLink:"https://onelink.shein.com/7/5povu9phm3j7",
  },

  {
    id: 13,
    image: "/images/women dress 13.jpg",
    title: "Romantic Yellow Gradient Floral Mesh Print Bodycon Stretch Backless Dress",
    description: "Aloruh This New Romantic Yellow Gradient Floral Mesh Print Bodycon Stretch Backless Dress, Adorned With Lace Trim, Is The Perfect Choice For Beach Vacations, Elegant Dates, Girls' Afternoon Tea, Music Festivals, And More. It's Ideal For Summer Getaways, Bohemian Trips, Wedding Guest Dresses, And Bridal Showers. It's Also Suitable For Summer Vacations And Everyday Wear.",
     productLink:"",
  },
  {
    id: 14,
    image: "/images/women dress 14.jpg",
    title: "Homecoming dresses,Hem Dress,Valentine's Day,Valentine Outfits For Women,Carnival dress",
    description: "Vintage Tie-Dye Butterfly Print Ruched Ruffle Hem Asymmetrical Hem Dress,Valentine's Day,Valentine Outfits For Women,Carnival,Carnival,Cocktail Dress,Dinner Dress,Prom Dress,Birthday Dress,Summer Dress,Party Dress,Vacation Outfits Woman 600+ sold 🎁60% OFF COUPON for every New User!",
     productLink:"https://onelink.shein.com/7/5pj1y2zhys8m",
  },
  {
    id: 15,
    image: "/images/15.jpg",
    title: "date night outfit",
    description: "2pcs Set Elegant Party Women's Striped Tie Clip, Fashionable Styling Spring White 100+ sold Elegant evening dress.",
     productLink:"https://onelink.shein.com/7/5pj1jm3c6w4h",
  },
  {
    id: 16,
    image: "/images/16.jpg",
    title: "summer outfit",
    description: "Sunnyshic 2pcs Women Spring & Summer Vacation Casual Daily Solid Color Linen Lightweight Button Down Collar Loose Long Sleeve Shirt & Low Waisted Shorts Set Fall Cloth For Women",
      productLink:"https://onelink.shein.com/7/5pj13lybavdo",
  },
  {
    id: 17,
    image: "/images/17.jpg",
    title: "Women's Light Blue Sexy Off-Shoulder Luxurious 3D Floral Elegant Romantic Party Maxi Dress",
    description: "Women's Light Blue Sexy Off-Shoulder Luxurious 3D Floral Elegant Romantic Party Maxi Dress, Suitable For Back To School, Valentine's Day, Spring & Summer",
     productLink:"https://onelink.shein.com/7/5pdjubsui9tc",
  },
  {
    id: 18,
    image: "/images/18.jpg",
    title: "Denim Dress Summer Sun Dresses For Women",
    description: "DAZY Women's V-Neck Single-Breasted Casual Pocket Strap Denim Dress Summer Sun Dresses For Women",
     productLink:"https://onelink.shein.com/7/5p71up4p4ff3",
  },
  {
    id: 19,
    image: "/images/19.jpg",
    title: "knuckle rings",
    description: "12pcs/Set Baroque Style French Faux Pearl Rings, Asymmetrical Elements & Lines Stackable Rings, For Women",
     productLink:"https://onelink.shein.com/7/5p72cahmaqrn",
  },
  {
    id: 20,
    image: "/images/20.jpg",
    title: "knuckle rings",
    description: "12pcs/Set Baroque Style French Faux Pearl Rings, Asymmetrical Elements & Lines Stackable Rings, For Women",
     productLink:"https://amzn.in/d/07M2Zj5X",
  },
  {
    id: 21,
    image: "/images/21.jpg",
    title: "knuckle rings",
    description: "12pcs/Set Baroque Style French Faux Pearl Rings, Asymmetrical Elements & Lines Stackable Rings, For Women",
     productLink:"https://fktr.in/ZgpqjU2",
  },

  {
    id: 22,
    image: "/images/22.jpg",
    title: "Homecoming dresses ,Trim A-Line Princess Dress, Summer Mini Dress, Garden Party Dress",
    description: "Glamine Charm Women's Organza Jacquard Metallic Trim A-Line Princess Dress, Summer Mini Dress, Garden Party Dress, Women's Wedding Guest Dress, Cocktail Party Dress, Back-To-School Tea Break Dress, Pink Floral Print Short Dress, Pink Dress, Summer Floral Dress, Pink Silk Dress, Peony Dress, Spring Dress Rose Dress Short Party Dress 3d Floral Dress Wedding Guest Party Dress Orchid Dress Short Spring Dress Pink Floral Dress",
     productLink:"https://onelink.shein.com/6/5p34j3xrjkzu",
  },
  {
    id: 23,
    image: "/images/23.jpg",
    title: "Women's Elegant Date Night Sleeveless Square Neck Dress",
    description: "Women's Elegant Date Night Sleeveless Square Neck Dress, Fitted Silhouette, Draping Curves, Skin-Friendly Comfort, Suitable For Daily Dates, Parties, Gatherings And Urban Strolls",
     productLink:"https://onelink.shein.com/6/5p34ukb86kb6",
  },
     {
    id: 24,
    image: "/images/24.jpg",
    title: "Versatile Solid Color High Waist Elastic Waistband Midi A-Line Skirt Casual Spring",
    description: "Versatile Solid Color High Waist Elastic Waistband Midi A-Line Skirt Casual Spring",
     productLink:"https://onelink.shein.com/6/5p35n2bar3g4",
    },
    {
    id: 25,
    image: "/images/25.jpg",
    title: "DONICY Women's White Solid Color Round Neck Ruffle Hem Short Sleeve Fitted Mermaid Midi Dress",
    description: "DONICY Women's White Solid Color Round Neck Ruffle Hem Short Sleeve Fitted Mermaid Midi Dress, Stretchy Knit Fabric, Medium Thickness, Elegant Fitted Dress Suitable For Spring, Summer, Autumn, Engagement, Date, Office Wear",
     productLink:"https://onelink.shein.com/6/5p358bjyzh90",
    },
    {
    id: 26,
    image: "/images/26.jpg",
    title: "Elegant, Glamorous, And Stylish, This Pink, Sequined Embroidered Dress",
    description: "Lovelzi Elegant, Glamorous, And Stylish, This Pink, Sequined Embroidered Dress Features Luxurious Satin Fabric, Handmade Pearl Embellishments, An Off-The-Shoulder Design, A Boning Waist, A Back Tie Detail, And A Pleated A-Line Silhouette. Suitable For Formal Occasions, Dates, Parties, Bachelorette Parties, Cocktail Parties, And Prom Dresses",
     productLink:"https://onelink.shein.com/6/5p36eoqvjgb1",
    },
    {
    id: 27,
    image: "/images/27.jpg",
    title: "Soft Girl Lounge Set 💛 | Cozy Chic Aesthetic Outfit Inspiration",
    description: "Comfy meets classy ✨ This buttery yellow lounge set is giving the perfect soft girl aesthetic with cozy luxury vibes 💛 The cropped tank, oversized cardigan, and flowy wide-leg pants create an effortless Pinterest-worthy look for coffee runs, casual days, or relaxing in style ☕ Minimal fashion lovers will absolutely adore this elegant neutral outfit inspiration 😍 ✔ Cozy & stylish look ✔ Clean girl aesthetic vibes ✔ Perfect for casual chic outfits ✔ Soft neutral color trend 2026 Save this outfit idea for your next comfy fashion inspo 🔥 🚀 Hashtags #SoftGirlStyle #CozyOutfits #PinterestFashion #LoungeSet #CleanGirlAesthetic #NeutralStyle #CasualChic #MinimalFashion #OutfitInspo #WideLegPants #AestheticOutfit #FashionInspo #ComfyStyle #OOTD #ViralFashion",
     productLink:"https://onelink.shein.com/6/5ow3j1fnl89y",
    },
     {
    id: 28,
    image: "/images/28.jpg",
    title: "Light Green Dress Features Luxurious Satin",
    description: "Lovelzi Elegant, Glamorous, Romantic, And Fashionable, This Light Green Dress Features Luxurious Satin And Mesh Trim, Handmade Sequined 3D Appliqué Embellishments, A Strapless Design, Off-The-Shoulder Style, Sheer Waist, And A Back Tie Detail. It's An A-Line Silhouette Suitable For Wedding Guests, Cocktail Parties, Birthday Parties, And Prom Dresses. Green Birthday Dress 🎁60% OFF COUPON for every New User! #homecoming dresses #homecoming outfits #minimalglamour dress #party outfit",
     productLink:"https://onelink.shein.com/6/5oom5gh44p3d",
    },

     {
    id: 29,
    image: "/images/29.jpg",
    title: "Homecoming dresses,",
    description: "Lovelzi Elegant, Luxurious, Noble, Palace-Style White Satin Open Shoulder Strapless Sweetheart Neckline Mermaid Silhouette Dress With Faux Pearl Decor, Flared Hem, Suitable For Bachelorette Party, Wedding, Graduation, Vacation, Bridal Shower 🎁60% OFF COUPON for every New User #homecoming dresses",
     productLink:"https://onelink.shein.com/6/5oolladqb5s2",
    },

     {
    id: 30,
    image: "/images/30.jpg",
    title: "Floral Pattern Strapless Dress Summer Belle Dress Love And Lemonade Dress",
    description: "Glamine Charm Women's Sleeveless Dress With Romantic 3D Embossed Floral Pattern Strapless Dress Summer Belle Dress Love And Lemonade Dress Yellow Wedding Guest Dress Short Yellow Dress Yellow Cocktail Dress,Beach Vacation Outfits For Women Birthday Dresses Evening Dresses Spring/Summer Dresses For Women Yellow Formal Dress Beautiful Dresses For Woman Cocktail Dresses 100+ sold 🎁60% OFF COUPON for every New User! #homecoming dresses #birthday outfit",
     productLink:"https://onelink.shein.com/6/5oomp6s8cidx",
    },

     {
    id: 31,
    image: "/images/31.jpg",
    title: "Women's Autumn/Winter New High Neck White Minimalist Commuter Style Sweater",
    description: "Women's Autumn/Winter New High Neck White Minimalist Commuter Style Sweater",
    productLink:"https://onelink.shein.com/6/5oky472pe4nx",
    },

     {
    id: 32,
    image: "/images/32.jpg",
    title: "Sexy Crop Top Floral Print Dress, Vacation Style Elegant Summer",
    description: "Sexy Crop Top Floral Print Dress, Vacation Style Elegant Summer",
     productLink:"https://onelink.shein.com/6/5okz26dv6qs9",
    },

     {
    id: 33,
    image: "/images/33.jpg",
    title: "summer, winter outfit",
    description: "Length Crop Pattern Solid Print or Pattern Type Solid Net Quantity (N) 1 Sleeve Styling Sleeveless Character Not Applicable Fabric Cotton Blend Neck/ Collar Shoulder Straps Sleeve Length Sleeveless Surface Styling Smocking Or Shirred Country of Origin India",
     productLink:"https://www.meesho.com/s/p/f03dx7?utm_source=ws",
    },
     {
    id: 34,
    image: "/images/34.jpg",
    title: "white tshirt, summer outfit",
    description: "Neck/ Collar Square Neck Sleeve Styling Regular Sleeves Print or Pattern Type Solid Ocassion Casual Sleeve Length Short Sleeves Pattern Solid Surface Styling Ruffles Net Quantity (N) 1 Character Not Applicable Generic Name Tops & Tunics Country of Origin India",
     productLink:"https://www.meesho.com/s/p/ecrsmt?utm_source=ws",
    },
     {
    id: 35,
    image: "/images/35.jpg",
    title: "long sleeves bodycon",
    description: "winter outfit and casual outfit",
     productLink:"https://www.meesho.com/s/p/52iz31?utm_source=ws",
    },
     {
    id: 36,
    image: "/images/36.jpg",
    title: "Elegant Beige Striped Jumpsuit Look 🤍 | Chic Summer Outfit Inspiration 2026",
    description: "Minimal, classy aur super stylish 💫 Yeh beige striped halter-neck jumpsuit ek perfect mix hai elegance aur modern fashion ",
     productLink:"https://onelink.shein.com/6/5oillhiwnxab",
    },
     {
    id: 37,
    image: "/images/37.jpg",
    title: "Sexy Lingerie Set Sequine Colorful Custom",
    description: "2 Pieces Custom Christmas Lady Backless Lace See-Through Sexy Lingerie Set Sequine Colorful Custom,Personalized,Unique,Customized Personalized Gifts For Men/Women,Lingerie,Panties,Underwear,Thongs Ideal Gifts For Her Girlfriend Living Room,Bedroom,For Anniversaries,For Birthdays,For Holiday 🎁60% OFF COUPON for every New User!",
     productLink:"https://onelink.shein.com/5/5ogtaance6fd",
    },
     {
    id: 38,
    image: "/images/38.jpg",
    title: "Solid Satin Spaghetti Strap Mermaid Maxi Dress, Elegant Cold Shoulder Draped Neck Evening Gown",
    description: "Solid Satin Spaghetti Strap Mermaid Maxi Dress, Elegant Cold Shoulder Draped Neck Evening Gown, Minimalist Romantic Summer Party Dress Pink",
     productLink:"https://onelink.shein.com/5/5oeutens6d64",
    },
     {
    id: 39,
    image: "/images/39.jpg",
    title: "customize lingerie, customize panties",
    description: "Customized White Lace Thong Panties, Personalized Lingerie Gift - Embroidered Floral Lace Underwear, Sexy Lingerie, Lovely Gift For Her, Bridal Shower Gift, Bridesmaid Gift, Valentine's Day Gift, Summer/Spring Lingerie, Lace Trim Thong, Unique Customized Gift, Bachelorette Party Favors",
     productLink:"https://onelink.shein.com/5/5ogst90qbpl4",
    },
     {
    id: 40,
    image: "/images/40.jpg",
    title: "summer outfit",
    description: "SEREN Summer New Knitted Camisole And Skirt Two Pieces Set, Women's Casual Sexy Vacation Beachwear, Summer Vacation Two Pieces Set, Women's Beachwear, Women's Summer Casual Set, Vacation Beachwear, Summer Outfits For Women, Vacation Outfits For Women, Beach Outfits For women",
     productLink:"https://onelink.shein.com/5/5oeucgz8e41s",
    },
     {
    id: 41,
    image: "/images/41.jpg",
    title: "Women's Green Knitted Jacquard Fabric Twist Front Cropped Top And Loose Skirt",
    description: "Elenzga Women's Green Knitted Jacquard Fabric Twist Front Cropped Top And Loose Skirt Set, Elegant And Stylish, Suitable For Birthday, Date, Party, Formal Occasion, Cocktail, Music Festival, Valentine's Day, Easter, Labor Day, Back To School Party, Single's Day, Spring Season",
     productLink:"https://onelink.shein.com/5/5oetynrfnn77",
    },
     {
    id: 42,
    image: "/images/42.jpg",
    title: "Soft Knit Cardigan For Autumn/Winter, Korean Style Casual",
    description: "Alicedudu Leisure Soft Knit Cardigan For Autumn/Winter, Korean Style Casual",
     productLink:"https://onelink.shein.com/5/5oesyblybwn9",
    },
     {
    id: 43,
    image: "/images/43.jpg",
    title: "Thong panties",
    description: "Women's Lace Patchwork Bow Tie Leopard Print Thong Panties",
     productLink:"https://onelink.shein.com/5/5obb7wsgrqrr",
    },
     {
    id: 44,
    image: "/images/44.jpg",
    title: "Waist Chain With Star Beads And Shell Beads",
    description: "Holiday Style Waist Chain With Star Beads And Shell Beads, A Women's Accessory Featuring A Conch Gemstone Waist Chain",
     productLink:"https://onelink.shein.com/5/5obco73y836l",
    },
     {
    id: 45,
    image: "/images/45.jpg",
    title: "panties , bikini set, romantic night outfit",
    description: "Romantic Purple Underwire Women's Bra And Panty Set, Sexy Lingerie",
     productLink:"https://onelink.shein.com/5/5obak2i14im2",
    },
     {
    id: 46,
    image: "/images/46.jpg",
    title: "Tie Crop Top And Pleated Side Slit Maxi Skirt",
    description: "abyoxi Deep V-Neck Backless Tie Crop Top And Pleated Side Slit Maxi Skirt, Fashionable 2-Piece Set Summer",
     productLink:"https://onelink.shein.com/5/5o9q42j5s6da",
    },
     {
    id: 47,
    image: "/images/47.jpg",
    title: "elegant bodycon dress",
    description: "abyoxi Women's Pink Ombre Mesh Splice Off-Shoulder Long Sleeve Fitted Mid-Length Dress, Sexy & Elegant, Suitable For Dates, Parties, Formal Dinners, Holidays, Valentine's Day, Spring/Summer, Bodycon",
     productLink:"https://onelink.shein.com/5/5o2aivxxnew7",
    },
     {
    id: 48,
    image: "/images/48.jpg",
    title: "A-Line Denim Shorts For Women Summer",
    description: "Mobula Sound #Sexy Music Festival Casual Fashion Distressed Y2K Youthful A-Line Denim Shorts For Women Summer",
     productLink:"https://onelink.shein.com/5/5o2a0wrsrivo",
    },
     {
    id: 49,
    image: "/images/49.jpg",
    title: "Swim Summer Beach Metallic Bikini Bottom",
    description: "SHEIN Swim Summer Beach Metallic Bikini Bottom",
     productLink:"https://onelink.shein.com/5/5o2avhr1m522",
    },
     {
    id: 50,
    image: "/images/50.jpg",
    title: "Long Sleeve Knitted Cardigan",
    description: "FOR BEAUTY Autumn/Winter New Solid Color Bow Tie Long Sleeve Knitted Cardigan, Fashion Minimalist Streetwear Casual Loose Fit, Suitable For Commuting, Women's Autumn Clothing Top Spring",
     productLink:"",
    },
     {
    id: 51,
    image: "/images/51.jpg",
    title: "Fitted Mermaid Dress",
    description: "abyoxi Pea Green Sexy Draped Open Back Tie Fitted Mermaid Dress, Suitable For Casual Daily Wear, New Spring/Summer Women Fashion Party Elegant",
     productLink:"https://onelink.shein.com/5/5o295u19wetf",
    },
     {
    id: 52,
    image: "/images/52.jpg",
    title: "Women's White Floral Ruffle Hem Midi Dress",
    description: "DONICY Women's White Floral Ruffle Hem Midi Dress, Square Neck Sleeveless Dress, Sweet Romantic Summer Holiday Dress 100+ sold",
     productLink:"https://onelink.shein.com/5/5nvfgubilfkl",
    },
     {
    id: 53,
    image: "/images/53.jpg",
    title: "Bodycon dress, High neck bodycon dress",
    description: "Women's Luxury Elegant Silver Metallic Bodycon Dress, High Neck Sleeveless Ruched Waist Design, Fashionable For Formal Occasions, Suitable For Spring/Summer, Festivals, Weddings #bodycon dress #date night outfit",
     productLink:"https://onelink.shein.com/5/5nveed7tiwws",
    },
    
     {
    id: 54,
    image: "/images/54.jpg",
    title: "Women's Sexy Hollow-Out Bustier Metal Decor Bodycon Dress",
    description: "Women's Sexy Hollow-Out Bustier Metal Decor Bodycon Dress, Long Vest Y2K Style Elegant Vacation Party Wedding Guest Cocktail Gown, Fashionable Hollow-Out Dress, Spring/Summer/Autumn #bodycon dress #autumn outfits #spring outfits #summer outfits",
     productLink:"https://onelink.shein.com/5/5nvf0gd9x0zt",
    },
    
     {
    id: 55,
    image: "/images/55.jpg",
    title: "knit top",
    description: "Women's Summer Solid Color Hollow Bat Sleeve Boat Neck Loose Cover Up Style Lightweight Mesh Sunscreen Knit Top, Relaxed Vibe, Minimalist Sexy Atmosphere, Sweet Cool Sexy Beach Holiday Travel",
     productLink:"https://onelink.shein.com/5/5nvi3fuuy14t",
    },
    
     {
    id: 56,
    image: "/images/56.jpg",
    title: "Women's Spring/Summer Sleeveless Zipper PleatedDress, Casual Elegant Style,SuitableFor Beach,Vacatio",
    description: "Women's Spring/Summer Sleeveless Zipper Pleated Dress, Casual Elegant Style, Suitable For Beach, Vacation, Date, Music Festival, Valentine's Day, Birthday Party And Other Occasions",
     productLink:"https://onelink.shein.com/5/5nvhot1lw316",
    },
    
     {
    id: 57,
    image: "/images/57.jpg",
    title: "Workout Set, Women's 2 Pieces Outfits",
    description: "UONNOU Seamless Workout Set, Women's 2 Pieces Outfits, Long Sleeve Crop Top With Thumbhole & High Waist Tummy Control Leggings, Contrast Line Sculpting Gym Yoga Activewear",
     productLink:"https://onelink.shein.com/5/5nvh2c2xovu7",
    },
    
     {
    id: 58,
    image: "/images/58.jpg",
    title: "Starfish & Seashell Beaded Necklace, boho jwellery",
    description: "Starfish & Seashell Beaded Necklace",
     productLink:"https://onelink.shein.com/4/5nr3irpp3m6r",
    },
    
     {
    id: 59,
    image: "/images/59.jpg",
    title: "pinstresty dresses, summer, spring, autumn outfit",
    description: "abyoxi Pink Sexy Deep V-Neck Backless A-Line Ruffle Hem Casual Maxi Dress, Waist Decorated With Floral Pattern, Suitable For Vacation, Beach, Travel, New Year, Valentine's Day And Other Occasions #summer outfits #romantiromantic aesthetic #spring outfits #autumn outfits #valentines day outfits",
     productLink:"https://onelink.shein.com/5/5nvghq7bdnp5",
    },
    
     {
    id: 60,
    image: "/images/60.jpg",
    title: "Bohemian Fashion Casual Dopamine Beaded Necklace, Suitable For Daily, Vacation, Travel, Casual Wear",
    description: "Bohemian Fashion Casual Dopamine Beaded Necklace, Suitable For Daily, Vacation, Travel, Casual Wear, Fashionable Jewelry Gift For Family And Friends",
     productLink:"https://onelink.shein.com/4/5nr4k1epqbye",
    },
    
     {
    id: 61,
    image: "/images/61.jpg",
    title: "Drop Shoulder Hollow Out Lightweight Knit Cardigan",
    description: "Drop Shoulder Hollow Out Lightweight Knit Cardigan",
     productLink:"https://onelink.shein.com/4/5nr4wz20akuy",
    },
    
     {
    id: 62,
    image: "/images/62.jpg",
    title: "Starfish & Shell Necklace, boho jwellery #beach jewelery,#boho jewellery",
    description: "Starfish & Shell Necklace, Handmade Minimalist Jewelry For Women, Suitable For Daily Wear And Beach Vacation #bohojewelry #boho style",
     productLink:"",
    },
    
     {
    id: 63,
    image: "/images/63.jpg",
    title: "spring outfit",
    description: "Brand LIBAS LIBAS Ideal For Women Women Length Type Mid Mid Brand Color Pink Pink Occasion Casual Casual Pattern Solid Solid Type Flared Flared Fabric Cotton Blend Cotton Blend Neck Square Neck Square Neck Pockets 1 1 Sleeve",
     productLink:"https://onelink.shein.com/4/5nr30asa54hz",
    },
    
     {
    id: 64,
    image: "/images/64.jpg",
    title: "Lime Green Summer Co-Ord Set 💚 | Beach Vacation Outfit Inspo 2026 #summeroutfit #vacationoutfit",
    description: "stunning lime green co-ord set 🌿 Perfect for beach days, vacations, brunch dates, and tropical getaways. The flowy off-shoulder crop top paired with comfy high-waisted shorts creates an effortlessly chic and trendy look. ",
     productLink:"https://onelink.shein.com/4/5nr27ss7lamg",
    },
    
     {
    id: 65,
    image: "/images/65.jpg",
    title: "Strapless Crop Top And Shorts Set",
    description: "Breezaya Women Fashionable Solid Color Strapless Crop Top And Shorts Set",
     productLink:"https://onelink.shein.com/4/5nka8av4okze",
    },
    
     {
    id: 66,
    image: "/images/66.jpg",
    title: "bikini,Swim Vcay New Textured Bubble Fabric Halter Neck Sexy Spaghetti Strap Bikini Swimwear",
    description: "Swim Vcay New Textured Bubble Fabric Halter Neck Sexy Spaghetti Strap Bikini Swimwear For Women, Suitable For Vacation For Summer",
     productLink:"https://onelink.shein.com/4/5nk9v99rutje",
    },
    
     {
    id: 67,
    image: "/images/67.jpg",
    title: "Sheer Mesh Open Front Long Sleeve Shirt, Camisole Top And Shorts Outfit Fall Cloth For Women",
    description: "Women's Sheer Mesh Open Front Long Sleeve Shirt, Camisole Top And Shorts Outfit Fall Cloth For Women",
     productLink:"https://onelink.shein.com/4/5nk98kez8t25",
    },
    
     {
    id: 68,
    image: "/images/68.jpg",
    title: "casual outfit, spring outfit",
    description: "Woven Khaki Backless Halter Top And Pants Casual Vacation Set For Women Two Piece Vacation Set Women Tan Two Piece Set Linen Two Piece Set Beige Two Piece Set Beach @SHEINofficial",
     productLink:"https://onelink.shein.com/4/5nh4g0s7e9t1",
    },
    
     {
    id: 69,
    image: "/images/69.jpg",
    title: "vacation outfit, casual outfit",
    description: "Spring/Summer Vacation Casual Fishbone Strap Top & Wide Leg Pants With Pockets 2 Pieces Set, Textured Fabric Material - B @SHEINofficial",
     productLink:"https://onelink.shein.com/4/5nh40iegiqtf",
    },
    
     {
    id: 70,
    image: "/images/70.jpg",
    title: "casual outfit for women",
    description: "Easowa VKing Button Front Vest And Bodycon Side Slit Skirt Colorblock Striped Casual Vacation Elegant Outfit For Women, Spring/Summer Striped Midi Dress Ribbed Midi Dress Bodycon Midi Dress Stripe Dress Summer Midi Dress",
     productLink:"https://onelink.shein.com/4/5nh3o4hh1n4k",
    },
     {
    id: 71,
    image: "/images/71.jpg",
    title: "Date night outfit, party outfit",
    description: "GlowEve Women's Satin V-Neck Faux Pearl Decor Spaghetti Strap Jumpsuit #date night outfit",
     productLink:"https://onelink.shein.com/4/5ncrjux5tmh7",
    },
     {
    id: 72,
    image: "/images/72.jpg",
    title: "High Neck Backless Bodycon Dress, Suitable For Vacation, Party And Date ,date night outfit",
    description: "Women's Sexy Elegant Mesh Floral Strapless Dress, Apricot High Neck Backless Bodycon Dress, Suitable For Vacation, Party And Date",
     productLink:"https://onelink.shein.com/4/5nd1mawjp6im",
    },
     {
    id: 73,
    image: "/images/73.jpg",
    title: "Women's Elegant Spaghetti Strap Mid-Length Dress, casual wear,long dress, simple look",
    description: "Women's Elegant Spaghetti Strap Mid-Length Dress, V-Neck Linen Texture A-Line Skirt, Backless High Waist Flowy Summer Beach Wedding Guest Cocktail Party Dress",
     productLink:"https://onelink.shein.com/4/5n9gl4f30phj",
    },
     {
    id: 74,
    image: "/images/74.jpg",
    title: "gold plated bracelet",
    description: "3pcs/Set Minimalist Geometric Asymmetrical Teardrop Shaped Metal Bangle Bracelet Set, Thick Solid Gold-Tone Alloy Material, Suitable For Women #bracelet ideas",
     productLink:"https://onelink.shein.com/4/5n9i0v09k8bs",
    },
     {
    id: 75,
    image: "/images/75.jpg",
    title:"bracelet",
    description: "3/1pc Vintage Minimalist Wavy Acrylic & Resin Material Bangle Bracelet Set, Suitable For Women's Daily Wear, Stackable, Perfect Gift Choice For Holidays",
     productLink:"https://onelink.shein.com/4/5n9hr5rseskz",
    },
     {
    id: 76,
    image: "/images/76.jpg",
    title: "pearl bracelet",
    description: "6pcs/Set Summer Beach Multilayer Stacked Pearl Bracelets, Fashionable Starfish & Shell Pendant Bracelet Set, Sexy Women Beach/Casual Date Jewelry Gift #bracelet ideas",
     productLink:"https://onelink.shein.com/4/5n9hh2q3peez",
    },
     {
    id: 77,
    image: "/images/77.jpg",
    title: "Poéselle Pink Dress,Summer Women Dresses,Sundress,Women's Elegant Floral Print",
    description: "Poéselle Pink Dress,Summer Women Dresses,Sundress,Women's Elegant Floral Print Maxi Slip Dress ",
     productLink:"https://onelink.shein.com/4/5n9gy7zgz862",
    },
     {
    id: 78,
    image: "/images/78.jpg",
    title: "Luxury Olive Green Fringe Dress ✨ Elegant Holiday Party Outfit Inspiration",
    description: "stunning olive green fringe dress — the perfect blend of glamour and sophistication. ✨ This strapless party outfit with shimmering details and layered fringe creates a luxe, high-fashion vibe ideal for Christmas parties, weddings, evening events, and special occasions chic holiday outfit or trending Pinterest fashion inspiration, this look is a must-save! 💚 Save this pin for your next party outfit idea and elevate your style game instantly. #LuxuryFashion #HolidayOutfit #PartyDress #EveningGown #GreenDress #ElegantStyle #FashionInspo #PinterestFashion #GlamLook #WinterOutfit #ChicStyle #OutfitInspiration #TrendingNow",
     productLink:"https://onelink.shein.com/4/5n8xy7xrgrvj",
    },
     {
    id: 79,
    image: "/images/79.jpg",
    title: "white summer dress",
    description: "Vintamour Vintage Elegant Women's Dress With Pockets Ditsy Floral Lapel Collar Button Closure Casual Commute Holiday Dress Summer Dresses For Women Summer Clothes Summer Outfits For Women Spring Clothing Spring Outfit Women Spring Dress Women Festival Outfits For Women Festival Dresses Elegant Dresses For Party Elegant Party Dresses Wedding Guest Dress For Women Graduation Dress Elegant Dresses For Women Dresses For Holiday Vacation Outfits Women Elegant Summer Dresses For Women Fleurora Spring And Summer Elegant Dress",
     productLink:"https://onelink.shein.com/3/5mzrn8ac61a9",
    },
     {
    id: 80,
    image: "/images/80.jpg",
    title: "Summer Dresses For Women",
    description: "Women's Solid Color Deep V Neck Ruched Design Sexy Dress,Summer Dresses For Women ",
     productLink:"https://onelink.shein.com/3/5mzqtsqqn5z8",
    },
     {
    id: 81,
    image: "/images/81.jpg",
    title: "Soleia Women's Casual Vacation Sexy Deep V-Neck Tie Halter Bow Tie Ruched Mini Dress, Suitable",
    description: "Women's Casual Vacation Sexy Deep V-Neck Tie Halter Bow Tie Ruched Mini Dress, Suitable For Beach, Cruise, Music Festival In Summer Yellow Halter Dress Yellow Sundress Sexy Sundress Yellow Beach Dress Yellow Vacation Dress,Date, Afternoon Tea,Dress For Holiday,Party,Nightclub Sexy Summer Dress,Island Vacation Outfit,Music Festival Outfit,Cruise Vacation Outfit,Party Outfit ",
     productLink:"https://onelink.shein.com/3/5mvvy8bg1ybp",
    },
     {
    id: 82,
    image: "/images/82.jpg",
    title: "casual outfit, casual summer outfit",
    description: "Women's Casual Cinched Waist Sleeveless Denim Dress, Summer Spring To Summer Valentine's Day Carnival Costume Commuting Vacation Graduation Chic Y2k Cute Streetwear Party Wedding Elegant Business Casual Woman Women's Sleeveless A-Line Denim Mini Dress With Chic Side Tie Detail Perfect For Summer Casual Wear",
     productLink:"",
    },
     {
    id: 83,
    image: "/images/83.jpg",
    title: "summer outfit, casual outfit",
    description: "Summer Sexy Spaghetti Strap Knit Midi Dress, European And American Style, Light Blue Vertical Ribbed, Sleeveless, Bodycon, Twist Back Hollow Design, French Elegant Vibe, Suitable For Dates, Commuting, Vacation, Formal Occasions Light Blue Summer Dress Cut-Out Maxi Dress Women Vacation Dress Beach Long Dress Baby Blue Maxi Dress Light Blue Maxi Dress Cut Out Maxi Dress Bodycon Summer Dress ",
     productLink:"https://onelink.shein.com/3/5muhlmlazazc",
    },
     {
    id: 84,
    image: "/images/84.jpg",
    title: "must have dress for everyday look 🌸",
    description: " Vintage Floral Print Casual Elegant Outfit For Women, Includes Round Neck Ruched Waist Blouse And Frill Waist Pocket Shorts ",
     productLink:"https://onelink.shein.com/3/5mvvapv6qezd",
    },
     {
    id: 85,
    image: "/images/85.jpg",
    title: "Elegant White Midi Dress Street Style | Chic Minimal Outfit Inspiration 🤍",
    description: "chic white ribbed midi dress featuring delicate black trim details. This timeless street-style look blends elegance with modern minimalism—perfect for brunch dates, city walks, or classy evening outings. A must-have outfit inspiration for anyone who loves clean, feminine fashion trends.",
    productLink:"https://onelink.shein.com/3/5mvv0sqld6qb",

    },
     
     {
    id: 86,
    image: "/images/86.jpg",
    title: "casual outfit for 2026",
    description: "Women's Simple Solid Color Camisole And Drawstring Waist Sweatpants Set Summer",
    productLink:"https://onelink.shein.com/3/5mvvmxv32dl5",
    },
     {
    id: 87,
    image: "/images/87.jpg",
    title: "casual outfit for 2026🌸🌸",
    description: "Elenzga Women's Summer Casual Striped Bandeau Wide Leg Jumpsuit",
    productLink:"https://onelink.shein.com/3/5muhzlq6pao0",
    },
     {
    id: 88,
    image: "/images/88.jpg",
    title: "casual look",
    description: "Soft, Breathable & Lightweight Fabric: Made from a blend of 60% Polyester, 35% Rayon, and 5% Spandex. Whether you're enjoying a summer day or lounging at home, this set's soft, breathable fabric keeps you cool and comfortable—just like your favorite summer dress or sundress, but with the easy flexibility of a two-piece Relaxed & Adjustable Fit: Designed with a loose-fitting top and shorts with an elastic waistband and drawstring",
    productLink:"https://a.co/d/02DICnaW",
    },
     {
    id: 89,
    image: "/images/89.jpg",
    title: "bodycon dress, bodycon dress outfit,elegant dress, minimal look 🌸✨",
    description: "Women's Elegant Floral Print Backless Dress Summer Summer Outfits Summer Clothes Beach Outfits For Woman Beach Vacation Vacation Outfits Woman Boho Tropical Vacation Woman Clothe Tropical Vacation Woman Clothe Wedding Anniversary Bridesmaid Party Date Sexy Wedding Guest Dress Women Bridal Shower Dress",
    productLink:"https://onelink.shein.com/3/5mr7fvul4rb3",
    },
     {
    id: 90,
    image: "/images/90.jpg",
    title: "white gown, white bodycon, casual look 🌸",
    description: "Poéselle Women's Ditsy Floral Contrast Lace V-Neck Sleeveless Fitted Mermaid Hem Elegant Dress,Floral Dress ,Valentines Day Dress,Casual Dresses For Woman, Elegant Dresses For Women, Casual Dresses For Women,Sun Dress ,Beach Dress, Vacation Outfits Women,Summer Dress,Summer Outfits For Women",
   productLink:"https://onelink.shein.com/3/5mr71czebmed",
  },
      {
    id: 91,
    image: "/images/91.jpg",
    title: "Romantic dress asthetic, romantic dress, casual outfit",
    description: "Poéselle Women's Romantic Yellow Ditsy Floral Ruched Waist Backless Halter Dress, Suitable For Vacation ",
    productLink:"https://onelink.shein.com/3/5mr8wlybp9o0",
    },
      {
    id: 92,
    image: "/images/92.jpg",
    title: "casual look, white gown , white dress, minimal look",
    description: "casual look, white gown , white dress, minimal look",
    productLink:"https://onelink.shein.com/3/5mr5t2qfhlxz",
    },
      {
    id: 93,
    image: "/images/93.jpg",
    title: "summer outfit, blue yellow flower print dress",
    description: "Yellow And Blue Floral Print Dress, Sleeveless Design, Square Neckline With Tie Detail, Fitted Bodice, Flared Skirt, Lightweight Fabric, Breathable Material, Vibrant Lemon Pattern, Summery Look, Casual Style, Soft Texture, Comfortable Fit, Playful Silhouette, Feminine Appeal, Colorful Print, Natural Fabric, Fresh And Bright, Lively Design, Flattering Shape, Youthful Charm, Easy-To-Wear Style.",
    productLink:"https://onelink.shein.com/3/5molbm0x4dtt",
    },
      {
    id: 94,
    image: "/images/94.jpg",
    title: "Vintage Blue Cottagecore Dress Aesthetic | Soft Girl Summer Outfit Inspiration",
    description: "Step into a dreamy cottagecore vibe with this elegant baby blue midi dress featuring puff sleeves and a flattering corset-style bodice. Paired with a wicker basket and fresh pink blooms, this look is perfect for garden dates, picnics, and soft aesthetic photoshoots. If you love vintage fashion, feminine outfits, and romantic styling, this look is pure inspiration for your Pinterest board.",
    productLink:"https://onelink.shein.com/3/5mokkbfj126d",
  },
      {
    id: 95,
    image: "/images/95.jpg",
    title: "Elegant Mama Tote Bags | Stylish Gift for Mom 💖",
    description: "These beautiful “Mama” tote bags are the perfect mix of style and sentiment 💕 Featuring floral heart designs and elegant gold lettering, these bags are ideal for everyday use or as a thoughtful gift for moms. From casual outings to special occasions, this aesthetic tote adds a chic touch to any outfit. Perfect for Mother’s Day, birthdays, or just to show love to mom 🌷",
    productLink:"https://onelink.shein.com/3/5mn8prh5u8m4",
    },
      {
    id: 96,
    image: "/images/96.jpg",
    title: "sexy swim suit, swimsuit,swim outfit , crochet",
    description: "Swim SXY Women's White Elegant Vacation Crochet Bra Cup Pearl Strap Dress",
    productLink:"https://onelink.shein.com/3/5mk5rl8teurm",
    },
      {
    id: 97,
    image: "/images/97.jpg",
    title: "bodycon, elegant dress, summer outfit",
    description: "Summer Women's Elegant Dress Lace Solid Color See-Through Long Elegant Women's Dress For Vacation And Date Valentine's Day Wedding Guest Dress For Women Black Dress Spring",
    productLink:"https://onelink.shein.com/3/5mkx81r7zgag",
    },
      {
    id: 98,
    image: "/images/98.jpg",
    title: "Embellished Mini Dress ✨ Beach Party Glam Outfit",
    description: "Shine effortlessly in this stunning embellished mini dress 💫 Perfect for beach parties, vacations, date nights, or luxury events. The delicate beadwork and elegant silhouette create a dreamy, glamorous look that stands out in every setting 🌊✨ Style it with minimal jewelry and soft glam makeup for a chic, high-end vibe. Save this look for your next summer outfit inspiration 💖 ",
    productLink:"https://onelink.shein.com/3/5mk542sk3bdi",
    },
      {
    id: 99,
    image: "/images/99.jpg",
    title: "Elegant Sequin Evening Dress ✨ Glam Party Outfit Inspiration",
    description: "Turn heads in this stunning sequin evening dress 💫 Perfect for parties, weddings, date nights, or special occasions. This body-hugging glam dress adds sparkle and elegance to your look, making you feel confident and stylish. Pair it with minimal accessories and heels for a classy, timeless vibe ✨ Save this look for your next event inspiration 💖",
    productLink:"https://onelink.shein.com/3/5mk446fbc2sa",
    },
      {
    id: 100,
    image: "/images/100.jpg",
    title: "casual outfit, versatile look, spring and summer outfit",
    description: "Casual Versatile Cropped Leggings Fall Spring Summer",
    productLink:"https://onelink.shein.com/2/5mg9djksvsw6",
    },
      {
    id: 101,
    image: "/images/101.jpg",
    title: "Beach waist chain 🌊, waist chain bikini waist chain",
    description: "Starfish Pendant Sexy Waist Chain Sexy Bikini Starfish Waist Chain Jewelry Sexy Belly Gold Body Chain Dress Set Metal Waist Belt Summer Beach Waist Jewelry For Women",
    productLink:"https://onelink.shein.com/2/5mg1t3e5ycd7",
    },
    {
    id: 102,
    image: "/images/102.jpg",
    title: "panties, customize panties, lingerie, customize thong, bikini tanga",
    description: "Customized Crystal Letter Sexy Lace Personalized Name Thong Panties, Bikini Tanga Lingerie T-Back Gift For Girlfriend, Wife, Valentine's Day, Christmas, Halloween, Thanksgiving, Birthday",
     productLink:"https://onelink.shein.com/5/5obbl0cv0soz",
    },
    {
    id: 103,
    image: "/images/103.jpg",
    title: "waist chain, beach waist chain bikini waist chain",
    description: "Gold Delicate Waist Chain Pearl Starfish Jewelry Bohemian Shell Summer Beach Waist Chain Suitable For Beach Vacation Wearing Great Beach Gift Summer Vacation Beach Pendant Necklace Beach Shell Jewelry",
    productLink:"https://onelink.shein.com/2/5mgbtidemgoy",
    },
    {
    id: 104,
    image: "/images/104.jpg",
    title: "Straight-Leg Jeans For Women.",
    description: "Straight-Leg Jeans For Women, American Design Loose Casual Wide-Leg Dragging Long Pants, jeans,pants",
    productLink:"https://onelink.shein.com/2/5mg9oq33uzv1",
    },
    {
    id: 105,
    image: "/images/105.jpg",
    title: "waist chain, pearl body chain, pearl waist chain, bikini chain",
    description: "Solid Color Pearl Waist Chain, Fashionable And Versatile Dress Accessory Office Wear Women",
    productLink:"https://onelink.shein.com/2/5mgcdgknu5u7",
    },
    {
    id: 106,
    image: "/images/106.jpg",
    title: "summer outfit, spring outfit, casual look 🌸",
    description: "Summer Tops Spring Summer Outfit For Women Festival Casual Blouses For Women Work Outfits For Women",
    productLink:"https://onelink.shein.com/2/5mclx3y5gcid",
    },
    {
    id: 107,
    image: "/images/107.jpg",
    title: "summer outfit",
    description: " Plus Size Women Stand Collar Cardigan Floral Embroidery Transparent Design Casual Top For Spring/Summer, Daily Home Leisure Vacation Wear, 2pcs Set Fall Cloth For Women",
    productLink:"https://onelink.shein.com/2/5m56dikteuqf",
    },
    {
    id: 108,
    image: "/images/108.jpg",
    title: "summer outfit ",
    description: "Airaco Elegant White Woven Fabric Two Piece Outfit Women's Blazer With Three Quarter Length Sleeve And Lapel Pocket Shorts ",
    productLink:"https://onelink.shein.com/2/5m56xula77lo",
    },
    {
    id: 109,
    image: "/images/109.jpg",
    title: "minimal nails, simple nails, nails for 2026",
    description: "3 PCS Black White Pink Heart Nail Art Stickers Hollow Heart 3D Nail Decals French Line Heart Sliders Simple Nail Art Decoration For Valentine Wedding Bride Manicure Tips Nails Nail Supplies 3.5k+ sold ",
    productLink:"https://onelink.shein.com/2/5m4sto6ptr8b",
    },
    {
    id: 110,
    image: "/images/101.jpg",
    title: "T-shirt, white tshirt, summer outfit, casual choice, casual outfit.",
    description: "Women's Casual Versatile Small Print Short Sleeve T-Shirt, Summer",
    productLink:"https://onelink.shein.com/2/5m1ftvkg91js",
    },
    {
    id: 111,
    image: "/images/101.jpg",
    title: "clutch, clutch bag,bag, purse",
    description: " Fashionable Metal Decor Mini Box Clutch Bag, Elegant Shiny Metal Bar Accent Women's Handbag, Luxury Feel For Evening Dress, Party, Wedding, Prom, Metallic Chain Included, Party Bags, Wedding Items",
    productLink:"https://onelink.shein.com/2/5m1gsyc8c5t8",
    },
    {
    id: 112,
    image: "/images/112.jpg",
    title: "bikini, pink bikini , summer vacation outfit, flower bikini, swimsuit.",
    description: "Swim Mod Women's Solid Color Beaded Halter Tie Back Sexy Bikini Set With Pearl Decor, Suitable For Beach Vacation Flower Swimsuit Bikini With Charm Kawaii Swimsuit Flower Bikini",
    productLink:"https://onelink.shein.com/2/5m1x7ae4j5sq",
    },
    {
    id: 113,
    image: "/images/113.jpg",
    title: "casual outfit, casual look, summer outfit",
    description: "INAWLY Women's Casual Solid Color Sleeveless Blouse, Summer ",
    productLink:"https://onelink.shein.com/2/5m1g8oasqo05",
    },
    {
    id: 114,
    image: "/images/114.jpg",
    title: "Perfect Summer Look 2026 Boho Crochet Cut-Out Dress – Ultimate Beach Babe Outfit",
    description: "Turn heads this summer with this stunning boho crochet cut-out dress. Featuring a halter neckline, fringe detailing, and a flattering body-hug fit, this outfit is perfect for beach days, vacations, and aesthetic summer photos. Style it with shell jewelry and a mini bag for that effortless coastal vibe. A must-have look for your Pinterest summer fashion inspiration board.",
    productLink:"https://onelink.shein.com/1/5lu179zq8b2i",
    },
    {
    id: 115,
    image: "/images/115.jpg",
    title: "summer sleepwear, night dress longuewear Sexy Charmeuse Pajama Set",
    description: "SilkySpell Contrast Color Lace Patchwork Deep V Floral Decor Sexy Charmeuse Pajama Set ",
    productLink:"https://onelink.shein.com/1/5lxbx4ush3jg",
    },
    {
    id: 116,
    image: "/images/116.jpg",
    title: "Chic Black & White Striped Shirt Outfit – Casual Summer Look",
    description: "Stay effortlessly stylish with this black and white striped button-up shirt paired with light denim jeans. This look is perfect for casual outings, brunch dates, or everyday fashion inspiration.",
    productLink:"https://onelink.shein.com/1/5lxdvo7kdlwt",
    },
    {
    id: 117,
    image: "/images/117.jpg",
    title: "Camisole, summer outfit.sexy outfits",
    description: "DEEKA Summer New Women's Fashion Sexy Satin Pleated Camisole Top",
    productLink:"https://onelink.shein.com/1/5lxcv07w309z",
    },
    {
    id: 118,
    image: "/images/118.jpg",
    title: "Casual Versatile Daily Wear Shirt, summer look, summer vacation, summer outfit",
    description: "GlowEve Women's Round Neck Geometric Embroidery Pattern Casual Versatile Daily Wear Shirt",
    productLink:"https://onelink.shein.com/1/5lxcf9y0r9do",
    },
    {
    id: 119,
    image: "/images/119.jpg",
    title: "bracelet",
    description: "4pcs/Set Vintage Simple Punk Style Thick Bracelet, Suitable For Women, Eternal Beauty Cuff Bracelet, Jewelry Accessories Gift Set, Daily Outfit. Note: The Metal Surface May Have Minor Scratches.",
    productLink:"https://onelink.shein.com/1/5lx8myw5le8o",
    },
    {
    id: 120,
    image: "/images/120.jpg",
    title: "Pajama Set For Women, Summer Loungewear.sleepwear,",
    description: "Satin Trim Collar Short Sleeve Top And Bow Tie Striped Shorts Pajama Set For Women, Summer Loungewear",
    productLink:"https://onelink.shein.com/1/5lu355o4uyy1",
    },
    {
    id: 121,
    image: "/images/121.jpg",
    title: "Glimmora Women's Tropical Fruit & Coconut Tree Print Beach Vacation Bandeau Top summer vacation",
    description: "Glimmora Women's Tropical Fruit & Coconut Tree Print Beach Vacation Bandeau Top",
    productLink:"https://onelink.shein.com/1/5lu8eepurqcy",
    },
    {
    id: 122,
    image: "/images/122.jpg",
    title: "Floral Bracelet for Women, A Vintage Style, casual choice",
    description: "This Elegant 925 Silver-Plated Floral Bracelet Is Suitable For Women, With A Vintage Style, Making It An Ideal Choice For Casual Wear And Vacations, As Well As A Great Gift For Valentine's Day.",
    productLink:"https://onelink.shein.com/1/5lu8yymg10fd",
    },
    {
    id: 123,
    image: "/images/123.jpg",
    title: "Apperloth Sexy Bohemian Style Contrast Striped Backless Knit",
    description: "A 2pcs Sexy Bohemian Style Contrast Striped Backless Knit Bralette With Ruffled Crochet Maxi Skirt Beach Cover Up Swimsuit ",
    productLink:"https://onelink.shein.com/1/5lu7z488d4ia",
    },
    {
    id: 124,
    image: "/images/124.jpg",
    title: "Perfect Summer Look 2026 Layered Ankle Bracelets For Women, Good Materials Layered Anklet",
    description: "4k Gold Dainty Layered Ankle Bracelets For Women, Good Materials Layered Anklet Bracelets For Women Pack Summer Beach Gold Jewelry Gift",
    productLink:"https://onelink.shein.com/1/5lu2i113btao",
    },
    {
    id: 125,
    image: "/images/125.jpg",
    title: "sleepwear Sleeveless Pajama Set For Women Multicolor Print Long Pants sleepwear",
    description: "Lullawish Boho Deep V Neck Sleeveless Pajama Set For Women Multicolor Random Print Long Pants With Ruffle Details Women Pajama Set Summer Two-Piece Sleepwear Floral Pajama Set Summer Lounge Sets For Women Women Sleepwear",
    productLink:"https://onelink.shein.com/1/5lfjkbf4ougu",
    },
    {
    id: 126,
    image: "/images/126.jpg",
    title: "Gold Bracelets For Women , asthetic jwellery, beach friendly bracelet",
    description: "3/4/5/6/7/15pcs Set Of Stacked Gold Bracelets For Women And Girls, Mixed Bead Shaped Pearl Bracelet With Gold Plated Elastic Bead Ball Bracelet Set, Daily Surprise Gift Jewelry",
    productLink:"https://onelink.shein.com/1/5lmu7x87v4lm",
    },
    {
    id: 127,
    image: "/images/127.jpg",
    title: "Boho Shell Waist Chain – Beach Style Layered Body Jewelry",
    description: "✨ Description: Elevate your beach look with this stunning boho-inspired waist chain featuring delicate cowrie shells, pearls, and gold-tone charms. Perfect for summer outfits, bikinis, crochet sets, or vacation styling, this layered body jewelry adds a chic coastal vibe. Ideal for beach days, festivals, or aesthetic Pinterest looks.",
    productLink:"https://onelink.shein.com/1/5lu0c5a6953r",
    },
    {
    id: 128,
    image: "/images/128.jpg",
    title: "summer asthetic,MainGRL Mustard Yellow Knit Casual Sleeveless Top For Women, Versatile For Summer",
    description: "MainGRL Mustard Yellow Knit Casual Sleeveless Top For Women, Versatile For Summer Babydoll Tops Cream Top Ruched Top Bow Top Women",
    productLink:"https://onelink.shein.com/1/5lh1p2a1l739",
    },
    {
    id: 129,
    image: "/images/129.jpg",
    title: "Red Hot Glam Outfit | Bold & Chic Night Look ❤️",
    description: "Turn heads with this stunning red gradient outfit ❤️🔥 This bold two-piece look blends elegance with confidence, perfect for night parties, vacation dinners, or glam photoshoots.",
    productLink:"https://onelink.shein.com/1/5lbo4ypoftq6",
    },
    {
    id: 130,
    image: "/images/130.jpg",
    title: "Minimal White Outfit Aesthetic | Chic Everyday Style Inspo",
    description: "Clean, minimal, and effortlessly chic 🤍 This all-white outfit featuring a soft cardigan and high-waisted jeans creates the perfect everyday aesthetic look. Ideal for casual outings, cozy vibes, and Pinterest-worthy minimal fashion inspiration.",
    productLink:"https://onelink.shein.com/1/5lfhr9dfyb74",
    },
    {
    id: 131,
    image: "/images/131.jpg",
    title: "European & American Style Women's Sleeveless Top, Design, Slim Fit Chic Asymmetrical",
    description: "European & American Style Women's Sleeveless Top, Design, Slim Fit Chic Asymmetrical Unique T-Shirt, Sexy And Versatile Summer",
    productLink:"https://onelink.shein.com/1/5lfhr9dfyb74",
    },
    {
    id: 132,
    image: "/images/132.jpg",
    title: "Elegant Beach Summer Outfit with Straw Hat 🤍🌾",
    description: "Chic and minimal beach look featuring a stylish white halter crop top paired with a flowy skirt and a woven straw hat with pearl details 👒✨ Perfect inspiration for summer vacations, beach photoshoots, and effortless aesthetic fashion.",
    productLink:"https://onelink.shein.com/1/5lbowt1dmzyu",
    },
    {
    id: 133,
    image: "/images/133.jpg",
    title: "Sexy Vintage Leopard Print Pattern Bikini 2 Pieces Set For Women Vacation Beach Summer",
    description: " Sexy Vintage Leopard Print Pattern Bikini 2 Pieces Set For Women Vacation Beach Summer",
    productLink:"https://onelink.shein.com/1/5lbkzggo5hjs",
    },
    {
    id: 134,
    image: "/images/134.jpg",
    title: "Soleia 2pcs Vacation Sexy Camisole Crochet Backless Top And Low Waist Skirt Set, Suitable date party",
    description: "Soleia 2pcs Vacation Sexy Camisole Crochet Backless Top And Low Waist Skirt Set, Suitable For Music Festival, Bohemian, Holiday, Date, Afternoon Tea",
    productLink:"https://onelink.shein.com/34/5l4f78ih729p",
    },
    {
    id: 135,
    image: "/images/135.jpg",
    title: "Slayform Women's Casual Contrast Color Trim Camisole Jumpsuit",
    description: "Slayform Women's Casual Contrast Color Trim Camisole Jumpsuit",
    productLink:"https://onelink.shein.com/1/5lbkkfu79r15",
    },
    {
    id: 136,
    image: "/images/136.jpg",
    title: "Women's Khaki Wave Beach Sun Hat With Faux Pearl & Bowknot Detail,Elegant Beach TravelVacationsunhat",
    description: "Elegant straw sun hat with a soft woven texture and delicate pearl accents 🌾✨ Perfect for beach days, summer vacations, and aesthetic photoshoots, this hat adds a classy and feminine touch while keeping you stylish under the sun.",
    productLink:"https://onelink.shein.com/1/5lbm7128oeoe",
    },
    {
    id: 137,
    image: "/images/137.jpg",
    title: "Summer Fresh Faux Pearl Necklace With Charms, Fashion Ocean Life Pendant Jewelry Set Suitable",
    description: "Summer Fresh Faux Pearl Necklace With Charms, Fashion Ocean Life Pendant Jewelry Set Suitable For Women Daily/Vacation Wear, Handmade Length Adjustable, Varying Number Of Faux Pearl Beads",
    productLink:"https://onelink.shein.com/34/5l4el3dzsemb",
    },
    {
    id: 138,
    image: "/images/138.jpg",
    title: "SEREN Spring And Summer New V-Neck Light Apricot Women's Knitted Top, Casual, Vacation, Elegant",
    description: "EREN Spring And Summer New V-Neck Light Apricot Women's Knitted Top, Casual, Vacation, Elegant, Fashionable, Simple, Three-Dimensional Metal Buttons, Knitted Fabric, Waist Cinching Version, Women's Knitted Top, Women's Top, Women's Knitted Shirt, Spring And Summer Women's Clothing, Commuting Office, Daily Street Going, Light And Mature Fashion",
    productLink:"https://onelink.shein.com/34/5l0jpmwrbsih",
    },
    {
    id: 139,
    image: "/images/139.jpg",
    title: "2pcs Women Summer Casual Solid Color Short Sleeve Top + High Waist Drawstring Long Pants 2PieceOutfit",
    description: "2pcs Women Summer Casual Solid Color Short Sleeve Top + High Waist Drawstring Long Pants 2PieceOutfit",
     productLink:"https://onelink.shein.com/34/5l0i665hdo2w",
    },
    {
    id: 140,
    image: "/images/140.jpg",
    title: "2pcs/Set Summer Casual Loose Fit Top And Shorts Sports Suit",
    description: "2pcs/Set Summer Casual Loose Fit Top And Shorts Sports Suit",
     productLink:"https://onelink.shein.com/34/5l0iz9uw5efa",
    },
     {
    id: 141,
    image: "/images/141.jpg",
    title: "MUSERA Extreme Wide Leg Jumpsuit Draped Front Bust Cups Cut Out Sides Open Back Vacation Boho Wester",
    description: "MUSERA Extreme Wide Leg Jumpsuit Draped Front Bust Cups Cut Out Sides Open Back Vacation Boho Western Spring Summer Vacation Beachwear Elegant Ibiza Holiday Wedding Guest Date Night Sexy Evening Bohemian Green Spring Summer Wedding Party Easter",
     productLink:"https://onelink.shein.com/34/5kyjscnn4zm3",
    },
     {
    id: 142,
    image: "/images/142.jpg",
    title: "Swim Lushoire Summer Vacation Blue & White Printed 1-Piece Tummy Control Swimdress",
    description: "Swim Lushoire Summer Vacation Blue & White Printed 1-Piece Tummy Control Swimdress",
     productLink:"https://onelink.shein.com/34/5kyl1kg4rq0g",
    },
     {
    id: 143,
    image: "/images/143.jpg",
    title: "Chic Red Gingham Maxi Dress Outfit for Summer Vibes",
    description: "Effortlessly stylish and perfect for warm days, this red gingham tiered maxi dress brings a soft, feminine charm. Paired with minimal sandals, it creates a breezy, relaxed look ideal for casual outings, vacations, or brunch dates. A must-have aesthetic outfit for a timeless summer wardrobe. ",
     productLink:"https://fktr.in/iFwurrf",
    },
     {
    id: 144,
    image: "/images/144.jpg",
    title: "Baroque Style French Faux Pearl Rings, Asymmetrical Elements & Lines Stackable Rings",
    description: "Baroque Style French Faux Pearl Rings, Asymmetrical Elements & Lines Stackable Rings",
     productLink:"https://onelink.shein.com/34/5ktytzbxjbws",
    },
     {
    id: 145,
    image: "/images/145.jpg",
    title: "Daily Wear, Head Accessories, Hair Accessories For Women, Claw Clips, Hairpin",
    description: "3pcs Vintage Faux Pearl Decor Starfish Shaped Hair Clip Stylish Hair Bun Maker Accessory, Suitable For Women And Girls For Daily Wear, Head Accessories, Hair Accessories For Women, Claw Clips, Hairpin ",
     productLink:"https://onelink.shein.com/34/5ktzej8jf338",
    },
     {
    id: 146,
    image: "/images/146.jpg",
    title: "Handmade Woven Women's Evening Bag, French Retro Fairy Faux Pearl Bag, Large Capacity",
    description: "Handmade Woven Women's Evening Bag, French Retro Fairy Faux Pearl Bag, Large Capacity Handbag & Shoulder Bag, Suitable For Outings, Dates, Shopping, Daily Matching, Office, Commuting, Gifts And More Occasions",
     productLink:"https://onelink.shein.com/34/5ktyg454omkg",
    },
     {
    id: 147,
    image: "/images/147.jpg",
    title: "FOR BEAUTY Summer New Women's Solid Ribbed Olive Green Knit Cardigan, Asymmetric Hem Design",
    description: "FOR BEAUTY Summer New Women's Solid Ribbed Olive Green Knit Cardigan, Asymmetric Hem Design, Fine Shiny Knit Fabric, Lightweight & Breathable, Slightly Loose Fit Suitable For Various Body Types, Vacation & Casual Style Top, Suitable For Holiday, Boho, Sexy, Summer Women's Clothing",
     productLink:"https://onelink.shein.com/34/5kqcp2d38awi",
    },
     {
    id: 148,
    image: "/images/148.jpg",
    title: "6-18pcs Gold-Tone Fashion Earrings Set, Stylish & Elegant, Suitable For Daily, Party, And EventWear",
    description: "6-18pcs Gold-Tone Fashion Earrings Set, Stylish & Elegant, Suitable For Daily, Party, And EventWear",
     productLink:"",
    },
     {
    id: 149,
    image: "/images/149.jpg",
    title: "Brown Aesthetic Bikini Set | Beach Vacation Outfit Inspo",
    description: "Stay effortlessly stylish with this chic brown aesthetic bikini set 🤎✨ Perfect for beach days, poolside vibes, and tropical vacations 🌊 The unique embroidered design adds a trendy and elegant touch, making it a must-have for summer fashion lovers. Pair it with a straw hat and minimal accessories for a complete Pinterest-worthy beach look.",
     productLink:"https://onelink.shein.com/34/5knq3oxrv32n",
    },
     {
    id: 150,
    image: "/images/150.jpg",
    title: "15pcs Geometric Asymmetrical Textured LiquidShape Heart Waterdrop Criss-Cross Multi-Layer Minimalis",
    description: "15pcs Geometric Asymmetrical Textured LiquidShape Heart Waterdrop Criss-Cross Multi-Layer Minimalis",
    productLink:"https://onelink.shein.com/34/5kpzjmw4bqsh",
    },
     {
    id: 151,
    image: "/images/151.jpg",
    title: "Chic Blue Top with White Pants | Minimal Summer Outfit Inspo",
    description: "Keep it classy and effortless with this chic blue top paired with white pants 💙🤍 Perfect for summer days, casual outings, and minimal aesthetic looks. The soft pastel tone adds a fresh and elegant vibe, while the simple styling makes it a go-to Pinterest outfit idea. Pair it with a mini bag and subtle jewelry for a trendy, clean girl look",
    productLink:"https://onelink.shein.com/34/5kqccud6gw01",
    },
      {
    id: 152,
    image: "/images/152.jpg",
    title: "Golden Conch Shaped Shoulder Bag, Detachable Shoulder Strap, Fashionable Lipstick Pouch, Elegant",
    description: "Golden Conch Shaped Shoulder Bag, Detachable Shoulder Strap, Fashionable Lipstick Pouch, Elegant",
    productLink:"https://onelink.shein.com/34/5kpz0m8e7arn",
    },
      {
    id: 153,
    image: "/images/153.jpg",
    title: "Elegant Beige One Shoulder Dress ",
    description: "Step into effortless elegance with this stunning beige one-shoulder dress 🤍✨ Perfect for classy outings, date nights, and minimal aesthetic looks. The soft neutral tone and sleek design create a timeless and sophisticated vibe. Pair it with delicate jewelry and heels for a chic, Pinterest-worthy outfit. Ideal for modern fashion lovers who love clean and elegant styles. ",
    productLink:"https://onelink.shein.com/34/5knqx0jb5uf1",
    },
      {
    id: 154,
    image: "/images/154.jpg",
    title: "Beige Crochet Co-ord Set",
    description: "Stay effortlessly stylish with this chic beige crochet co-ord set 🤍 Perfect for beach vacations, summer outings, and aesthetic photoshoots. The textured crop top paired with a fringe skirt gives a trendy boho vibe 🌿✨ Style it with minimal accessories, flats, and a woven bag for a complete Pinterest-worthy summer look. Ideal for vacation fashion inspiration and casual chic outfits.",
    productLink:"https://onelink.shein.com/34/5kk4slbq84s3",
    },
      {
    id: 155,
    image: "/images/155.jpg",
    title: "Blue Tropical Summer Dress Outfit",
    description: "Turn heads this summer with this stunning blue and white tropical dress 🌊💙 Perfect for beach days, vacations, and sunny outings, this outfit gives a fresh, elegant, and Pinterest-worthy vibe. Pair it with a woven bag and minimal jewelry for the ultimate summer aesthetic look. Ideal for resort wear, casual dates, or holiday styling inspiration.",
   productLink:"https://onelink.shein.com/34/5kk2r9cd86kc",
  },
      {
    id: 156,
    image: "/images/156.jpg",
    title: "Boho Waist Chain Jewelry | Beach Body Chain Aesthetic Look",
    description: "Elevate your beach style with this stunning boho waist chain ✨ Perfect for bikini looks, beach vacations, and summer aesthetic vibes 🌊💛 The delicate gold chain with pearl details adds a touch of elegance and femininity. Style it with swimwear or crop tops for a trendy, Pinterest-worthy look. Ideal for vacation fashion, beach outfits, and boho jewelry lovers. ",
    productLink:"https://onelink.shein.com/34/5kmds1drgc4r",
  },
      {
    id: 157,
    image: "/images/157.jpg",
    title: "Cute Pink Summer Dress Outfit ",
    description: "GlowEve Women's Solid Color V-Neck Tie Strap Sleeveless Fashionable Ruffle Hem Dress ",
    productLink:"https://onelink.shein.com/34/5kk721bnlo41",
    },
      {
    id: 158,
    image: "/images/158.jpg",
    title: "Elegant White Minimal Outfit | Chic Summer Street Style Look 🤍",
    description: "This effortlessly chic outfit features a sleek white camisole paired with high-waisted denim jeans and a cozy knit cardigan — the perfect balance of comfort and style. 🤍✨ Ideal for casual outings, coffee dates, or aesthetic street-style inspiration. ✔ Minimal fashion ✔ Clean girl aesthetic ✔ Summer outfit inspo ✔ Casual chic style Save this look for your everyday fashion inspiration! 💫",
    productLink:"https://onelink.shein.com/34/5kjfeae4y9gm",
  },
      {
    id: 159,
    image: "/images/159.jpg",
    title: "Mejors Women's French Fashion Casual Cute Shiny Textured Asymmetric Hem Round Neck Sleeveless Knit",
    description: "Mejors Women's French Fashion Casual Cute Shiny Textured Asymmetric Hem Round Neck Sleeveless Knit Camisole, Suitable For Vacation Wear, Essential For Summer ",
    productLink:"https://onelink.shein.com/34/5kiruis2bhms",
  },
      {
    id: 160,
    image: "/images/160.jpg",
    title: "Beach Waist Chain Trend 🌊 | Aesthetic Summer Body Jewelry",
    description: "Upgrade your beach look with these stunning layered waist chains featuring pearls and shell details ✨ Perfect for summer outfits, vacation vibes, and aesthetic styling. Pair it with crochet skirts or bikinis for that viral beach look 🌴 Save now & shop this trendy accessory before it sells out!",
    productLink:"https://onelink.shein.com/4/5nroxuzirktu",
  },
      {
    id: 161,
    image: "/images/161.jpg",
    title: "Viral Black Mini Dress 🖤 ",
    description: "Turn heads with this stunning black mini dress featuring a deep V neckline and elegant gold detail ✨ Perfect for date nights, parties, and evening outings. This trendy outfit is a must-have for every fashion lover 💃 Save now & shop the look before it sells out!",
    productLink:"https://onelink.shein.com/34/5kf71ia8gf2t",
    },
     {
    id: 162,
    image: "/images/162.jpg",
    title: "4pcsSexy Solid Color Bikini Set With Sheer Cover-Up, Suitable For Vacation, Beach Party, Also Ideal",
    description: "4pcs Sexy Solid Color Bikini Set With Sheer Cover-Up, Suitable For Vacation, Beach Party, Also Ideal For New Year And Valentine's Day, Exuding Elegance And Avant-Garde, Perfect Choice For Casual Women In Spring/Summer White ",
    productLink:"https://onelink.shein.com/34/5kf66vby8m5c",
    },

     {
    id: 163,
    image: "/images/163.jpg",
    title: "Soleia Shell Cup Tassel Hem Spaghetti Strap Fitted Mini Dress, Bohemian",
    description: "Soleia Shell Cup Tassel Hem Spaghetti Strap Fitted Mini Dress, Bohemian, Boho, Vacation, Suitable For Valentine's Day Date, Spring/Summer ",
    productLink:"https://onelink.shein.com/34/5kengqft2ulq",
    },

     {
    id: 164,
    image: "/images/164.jpg",
    title: "SASSAFRAS Printed Women Jumpsuit",
    description: "Bright tropical vibes 🌺✨ Flowy floral mini dress with a breezy silhouette—perfect for sunny days, vacations, and effortless summer style 🌿☀️",
    productLink:"https://fktr.in/SdzpOej",
    },

     {
    id: 165,
    image: "/images/165.jpg",
    title: "Bikini Village Bikini Solid Women Monokini Black Swimsuit",
    description: "Color Black Black Fabric Nylon Nylon Pattern Solid Solid Type Monokini Monokini Style Code XFG-981-Black XFG-981-Black Model Name Bikini Bikini Secondary Color Black Black Occasion Lifestyle Lifestyle Brand Bikini Village Bikini Village Brand Color Black Black Ideal For Women Women Size 3XL 3XL Product Details Bust Size 44 inch 44 inch Lining NA",
    productLink:"https://fktr.in/w6wvp9c",
    },

     {
    id: 166,
    image: "/images/166.jpg",
    title: "Women's Vacation Halter Floral Print Layered Ruffle Hem Dress Elegant Summer",
    description: "Women's Vacation Halter Floral Print Layered Ruffle Hem Dress Elegant Summer",
    productLink:"https://onelink.shein.com/43/5vx3tjm7g8zg",
    },

     {
    id: 167,
    image: "/images/167.jpg",
    title: "Cream Yellow Loose Sweatshirt + Pleated Skirt",
    description: "Cream Yellow Loose Sweatshirt + Pleated Skirt | Cute Matching 2 Pieces Set | Suitable For Campus, Airport Travel And Casual Daily Wear | Essential For Casual Street Style Elegant Winter",
    productLink:"https://onelink.shein.com/43/5vx7vxprwktt",
    },

     {
    id: 168,
    image: "/images/168.jpg",
    title: "black leather jacket",
    description: "Women's Summer PU Leather Jacket, Windproof Moto Biker Coat With Lapel Collar, Zipper Closure, Elastic Hem, Loose Slim Fit, Casual Commuter Outerwear",
    productLink:"https://onelink.shein.com/43/5vxdkt3abwon",
    },

     {
    id: 169,
    image: "/images/169.jpg",
    title: "black leather jacket",
    description: "Women's Casual Elegant Black Faux Leather Jacket, High Collar Loose Fit, Office Outerwear, Street Style, Holiday Vacation Style, Spring Autumn Winter",
    productLink:"https://onelink.shein.com/43/5vxe28j4p0s6",
    },

     {
    id: 170,
    image: "/images/170.jpg",
    title: "DAZY Autumn/Winter New Loose Casual Thickened PU Women's Regular Outerwear Jacket School",
    description: "DAZY Autumn/Winter New Loose Casual Thickened PU Women's Regular Outerwear Jacket School",
    productLink:"https://onelink.shein.com/43/5vxec1pnpxgn",
    },

     {
    id: 171,
    image: "/images/171.jpg",
    title: "Elegant Casual Women's Summer Sleeveless A-Line Dress With Spaghetti Strap For Concert, Party",
    description: "Elegant Casual Women's Summer Sleeveless A-Line Dress With Spaghetti Strap For Concert, Party And Birthday",
    productLink:"https://onelink.shein.com/43/5vxetwxqmu4i",
    },
     {
    id: 172,
    image: "/images/172.jpg",
    title: "PARTHEA Cold Shoulder Ruffle Trim Ruched Mesh Bodycon Dress Summer Elegant Party",
    description: "PARTHEA Cold Shoulder Ruffle Trim Ruched Mesh Bodycon Dress Summer Elegant Party",
    productLink:"https://onelink.shein.com/43/5vxf87wsfdxa",
    },
     {
    id: 173,
    image: "/images/173.jpg",
    title: "Vacation Style Starfish Seashell Random Pearl Quantity Based On Size Length Jewelry Back Chain",
    description: "Vacation Style Starfish Seashell Random Pearl Quantity Based On Size Length Jewelry Back Chain",
    productLink:"https://onelink.shein.com/43/5w12td84bnk3",
    },
     {
    id: 174,
    image: "/savana/1.webp",
    title: "A-Line Dress",
    description: "beatiful A-Line Dress .for special occasion.",
    productLink:"https://www.savana.com/details/a-line-dress-1863632?vid=6&skcPGs=306808-406197,317125-417291,317126-417292",
    },
     {
    id: 175,
    image:  "/savana/2.webp",
    title: "Pastel Pink Shirt with Knit Scarf | Elegant Women's Fashion",
    description: "Upgrade your everyday wardrobe with this pastel pink button-down shirt featuring a stylish knit scarf detail. Perfect for casual outings, office wear, brunch dates, and chic street style. Save this outfit inspiration for your next look. 💖",
    productLink:"",
    },
     {
    id: 176,
    image: "/savana/3.webp",
    title: "Chic Black Crop Top & Beige Wrap Pants Outfit for Women.belted pant",
    description: "Turn heads with this effortlessly chic outfit featuring a fitted black crop top and stylish beige wrap pants. The clean silhouette and neutral colour palette make this look perfect for brunch dates, shopping, vacations, casual office days, dinner outings, and modern street style. Pair it with heels, a classic shoulder bag, and gold accessories for a timeless fashion statement that's both elegant and versatile.",
    productLink:"https://www.savana.com/details/belted-culotte-pants-2255342?vid=25&skcPGs=369826-472259,376241-482981",
    },
     {
    id: 177,
    image:"/savana/4.webp", 
    title: "Elegant Beige Embroidered Blouse with Wide-Leg Trousers.3D Floral Placket Blouse (Luxury Elegant Style)",
    description: "Create a sophisticated look with this elegant beige blouse featuring delicate floral embroidery and flowing long sleeves, perfectly paired with tailored wide-leg trousers. This timeless outfit blends luxury and comfort, making it ideal for office wear, dinner dates, formal events, business casual looks, and elegant everyday fashion. Style it with statement earrings and neutral heels for a polished, modern outfit you'll want to save for future inspiration.",
    productLink:"https://www.savana.com/details/3d-floral-placket-blouse-(luxury-elegant-style)-2178432?vid=11&skcPGs=357837-461284",
    },
     {
    id: 178,
    image: "/savana/5..webp",
    title: "Black Sweater Vest with Striped Shirt & Wide-Leg Jeans Outfit",
    description: "Upgrade your everyday wardrobe with this effortlessly chic outfit featuring a classic black sweater vest layered over a striped button-down shirt and paired with light wash wide-leg jeans. Finished with brown heels, a leather shoulder bag, and stylish sunglasses, this timeless look is perfect for work, coffee dates, college, shopping, and casual weekends. Save this outfit for your next fashion inspiration!",
    productLink:"https://www.savana.com/details/fake-2-pcs-blouse-2103462?vid=24&skcPGs=346432-448810",
    },
     {
    id: 179,
    image: "/savana/6..webp",
    title: "Elegant Blush Pink Off-Shoulder Mermaid Dress | Romantic Evening & Party Fashion",
    description: "Turn heads with this elegant blush pink off-shoulder mermaid dress featuring delicate floral sleeves and a flattering fitted silhouette. Perfect for weddings, evening parties, prom, formal events, cocktail nights, and special occasions. Save this stunning fashion inspiration for your next glamorous look and discover timeless feminine style. blush pink dress, off shoulder dress, mermaid dress, evening gown, formal dress, prom dress, wedding guest dress, elegant fashion, party outfit, cocktail dress, feminine style, luxury fashion, pink gown, outfit inspiration, fashion trends",
    productLink:"https://www.savana.com/details/lettuce-edge-fishtail-dress-2262462?vid=122&skcPGs=370715-473254",
    },
     {
    id: 180,
    image: "/savana/7.webp",
    title: "Women's Cream Faux Leather Moto Jacket | Chic Casual & Fall Fashion Outfit",
    description: "Elevate your wardrobe with this elegant cream faux leather moto jacket featuring a sleek zip-front design, quilted shoulder details, and a timeless tailored fit. Perfect for autumn, winter, casual outings, travel, brunch, and smart everyday looks. Pair it with skirts, jeans, or trousers for an effortlessly sophisticated style that never goes out of fashion.",
    productLink:"https://www.savana.com/details/faux-leather-jacket-2096932?vid=308&skcPGs=345321-448852,345322-448853",
    },
     {
    id: 181,
    image: "/savana/8.webp",
    title: "Light Wash Cropped Denim Moto Jacket | Trendy Women's Street Style Outfit",
    description: "Upgrade your everyday wardrobe with this stylish light wash cropped denim moto jacket. Featuring a modern biker-inspired design, oversized fit, and versatile blue wash, it's the perfect layering piece for casual days, street style, travel, coffee dates, and weekend outfits. Pair it with leather pants, jeans, skirts, or dresses to create effortlessly chic looks all year round.",
    productLink:"https://www.savana.com/details/asymmetric-faux-leather-jacket-1440992?vid=260&skcPGs=241423-108764",
    },
     {
    id: 182,
    image: "/savana/s10.webp",
    title: "Beige Hooded Windbreaker Jacket | Minimalist Casual Outfit",
    description: "Stay effortlessly stylish with this beige hooded windbreaker jacket paired with a neutral mini dress. A perfect minimalist outfit for everyday wear, travel, spring, and casual street style inspiration",
    productLink:"https://www.savana.com/details/hooded-windbreaker-jacket-2084672?vid=11&skcPGs=343289-445843,362674-465262,362686-465263,374600-479515,374601-479516,374602-479517",
    },
     {
    id: 183,
    image: "/savana/10.webp",
    title: "Hooded Windbreaker Jacket",
    description: "Design Detail HoodedMain FabricFlat WovenStretchabilityNot StretchableFit TypeRelaxed FitQuantity1 PieceBeltDoes not come with Belt",
    productLink:"https://www.savana.com/details/hooded-windbreaker-jacket-2282912?vid=313&skcPGs=373554-478378",
    },
    {
    id: 184,
    image: "/savana/11.webp",
    title: "Elegant Blush Pink Satin Off-Shoulder Mermaid Maxi Dress ✨",
    description: "Turn heads in this elegant blush pink satin off-shoulder mermaid dress, designed with a flattering fitted silhouette and luxurious silky finish. Perfect for weddings, formal parties, prom, evening events, and special occasions. Save this timeless fashion inspiration for your next elegant outfit idea.",
    productLink:"https://www.savana.com/details/gathered-a-line-dress-2162532?vid=6&skcPGs=355568-457436",
    },
    {
    id: 185,
    image: "/savana/12.webp",
    title: "Elegant Pink Textured Sleeveless Mini Dress for Chic Party Looks 💖",
    description: "The dress is presented as a clean, high-quality Pinterest fashion editorial with a polished model pose and soft, elegant lighting that highlights its texture and silhouette.",
    productLink:"",
    },
     {
    id: 186,
    image: "/savana/13.webp",
    title: "Contrast Checkered Off Shoulder Flared Hem Mini Dress",
    description: "Elevate your wardrobe with this stylish black off-shoulder mini dress featuring eye-catching blue plaid long sleeves and a flattering fit-and-flare silhouette. Perfect for date nights, parties, casual chic outings, and fashion-forward street style. Save this unique outfit inspiration for your next statement look.",
    productLink:"https://littleboxindia.com/collections/dresses/products/contrast-checkered-sleeve-off-shoulder-mini-dress",
    },
     {
    id: 187,
    image: "/savana/14.webp",
    title: "Halter Neck Tiered Ruffle Mini Dress in Sage Green",
    description: "Halter Neck Tiered Ruffle Mini Dress in Sage Green₹ 1,199",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/halter-neck-tiered-ruffle-mini-dress-in-sage-green",
    },
     {
    id: 188,
    image: "/savana/15.webp",
    title: "Halter Cowl Neck Satin Maxi Dress in Lilac",
    description: "Halter Cowl Neck Satin Maxi Dress in Lilac",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/halter-cowl-neck-satin-maxi-dress-in-lilac",
    },
     {
    id: 189,
    image: "/savana/16.webp",
    title: "Sleeveless V Neck Satin Midi Dress in Classic White",
    description: "Sleeveless V Neck Satin Midi Dress in Classic White is the perfect blend of timeless elegance and modern sophistication. Crafted from smooth polyester satin with a luxurious sheen, this sleeveless V neck satin midi dress features a flattering deep V-neckline, a sleeveless silhouette, and a fitted bodice accented with fabric-covered buttons for a refined finish. The pleated A-line midi skirt flows beautifully with every step, creating graceful movement that makes this sleeveless V neck satin midi dress an ideal choice for weddings, cocktail parties, evening celebrations, and formal occasions.",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/sleeveless-v-neck-satin-midi-dress-in-classic-white",
    },
     {
    id: 190,
    image: "/savana/17.webp",
    title: "Square Neck Button Front Peplum Top in Classic White",
    description: "Square Neck Button Front Peplum Top is the perfect mix of polished charm and everyday elegance. Crafted in a breathable, structured fabric, this square neck button front peplum top features a flattering square neckline, statement gold-tone button front, delicate ruffle cap sleeves, and a fitted bodice that flows into a feminine peplum hem. The tailored silhouette enhances your waist while offering a comfortable fit, making this square neck button front peplum top an effortless choice for brunch dates, office styling, and weekend outings.",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/square-neck-button-front-peplum-top-in-classic-white",
    },
     {
    id: 191,
    image: "/savana/18.webp",
    title: "High Neck Full Sleeve Top and Wide Leg Pants Set in Black",
    description: "Refine your everyday style with this High Neck Full Sleeve Top and Wide Leg Pants Set in Black , designed for a sleek and polished look. Crafted from polyester, it offers a smooth texture with a lightweight and comfortable feel. The high neck top with full sleeves adds a touch of sophistication, while the wide leg pants create a flowing, relaxed silhouette that enhances movement and comfort. The coordinated design ensures a clean, put-together appearance with minimal effort.Perfect for work, travel, or smart-casual outings, this set blends modern simplicity with timeless appeal..",
    productLink:"https://littleboxindia.com/collections/matching-sets/products/high-neck-full-sleeve-top-and-wide-leg-pants-set-in-black",
    },
    {
    id: 192,
    image: "/savana/19.webp",
    title: "✨ Elegant Butter Yellow Halter Maxi Dress | Chic Summer Outfit Inspiration",
    description: "Step into effortless elegance with this stunning butter yellow halter maxi dress. Featuring delicate lace trim, a flattering fitted silhouette, and a graceful flowing skirt, this look is perfect for summer vacations, brunch dates, garden parties, and beachside evenings. The face-hidden phone pose adds a trendy, aesthetic touch while keeping the focus on the outfit. Save this look for your next fashion inspiration and discover more timeless dress ideas..",
    productLink:"https://www.savana.com/details/tie-up-a-line-dress-2234382?vid=313&skcPGs=366836-470965",
    },
     
    {
    id: 193,
    image: "/savana/20.webp",
    title: "🌼 Soft Yellow Ruffle Maxi Dress | Elegant Summer Home Outfit Inspiration",
    description: "Bring effortless elegance into your wardrobe with this beautiful soft yellow ruffle maxi dress. Featuring delicate ruffle details, a flowing silhouette, and a feminine design, it's perfect for summer days, casual brunches, vacations, and cozy at-home photoshoots. The face-hidden phone pose creates a modern, aesthetic look while keeping the focus on the outfit. Save this inspiration for your next chic summer style..",
    productLink:"https://www.savana.com/details/ruffle-a-line-dress-2269532?vid=313&skcPGs=371671-474304",
    },
     
    {
    id: 194,
    image: "/savana/21.webp",
    title: "Bell Bottom Pocket Structured Pants in Coco",
    description: "Bell Bottom Pocket Structured Pants in Coco are bold, polished, and made for statement styling. These bell bottom pants feature a high waist design that defines your silhouette while keeping the look structured and elegant. The wide bell bottom shape creates dramatic movement and a flattering elongated look. .",
    productLink:"https://littleboxindia.com/collections/all-clothing/products/bell-bottom-pocket-structured-pants-in-coco",
    },
     
    {
    id: 195,
    image: "/savana/22.webp",
    title: "Cowl Neck Draped Mini Dress in Chocolate Brown",
    description: "Turn heads with this Cowl Neck Draped Mini Dress in Chocolate Brown. Designed with a sleek, figure-skimming silhouette, this elegant mini dress features a softly draped cowl neckline that creates a sophisticated focal point. Gentle ruching through the waist enhances the fit, while the sleeveless design and subtly flared hem lend a graceful finish. Chic and effortlessly refined, it's a timeless piece made for memorable occasions..",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/cowl-neck-draped-mini-dress-in-chocolate-brown",
    },
     
    {
    id: 196,
    image: "/savana/23.webp",
    title: "Ruffle Peplum Top and Midi Skirt Co-ord in Wine Maroon",
    description: "Ruffle Peplum Top and Midi Skirt Co-ord in Wine Maroon brings timeless elegance with a soft, feminine touch. Crafted from lightweight polyester fabric, this matching set features a floral print peplum top with a flattering V-neckline, delicate ruffle detailing, and puff sleeves for a romantic silhouette. The coordinating button-front midi skirt completes the look with graceful movement and a polished finish. This floral ruffle peplum top and midi skirt co-ord is perfect for creating an effortlessly chic outfit with minimal styling..",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/ruffle-peplum-top-and-midi-skirt-co-ord-in-wine-maroon",
    },
     
    {
    id: 197,
    image: "/savana/24.webp",
    title: "Textured Stripe Halter Crop Top in Sage Green",
    description: "Textured Stripe Halter Crop Top is your go-to pick for effortless everyday styling with a trendy twist. Designed in a soft textured fabric, this textured stripe halter crop top features a flattering halter neckline, subtle striped pattern, and a body-hugging fit that enhances your silhouette. The cropped length keeps the look fresh and versatile, making this textured stripe halter crop top perfect for casual outings, vacations, or weekend plans. Lightweight and comfortable, it pairs easily with everything from cargo pants to denim and skirts for an elevated Gen-Z aesthetic..",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/textured-stripe-halter-crop-top-in-sage-green",
    },
     
    {
    id: 198,
    image: "/savana/25.webp",
    title: "Textured Short Sleeve Crop Top in Light Green",
    description: "Textured Short Sleeve Crop Top is the perfect blend of comfort and everyday style. Crafted from a soft textured fabric with a flattering cropped silhouette, this textured short sleeve crop top features subtle gathered detailing at the waist for a figure-enhancing fit. The relaxed short sleeves and classic round neckline make this textured short sleeve crop top an effortless pick for casual days, coffee runs, or weekend outings. Lightweight and easy to wear, it pairs seamlessly with everything from denim to cargo pants for an on-trend Gen-Z look.Style it with wide-leg jeans, mini skirts, or linen trousers for an easy outfit that works from day to night..",
    productLink:"https://littleboxindia.com/collections/new-arrivals/products/textured-short-sleeve-crop-top-in-light-green",
    },
     
    {
    id: 199,
    image: "/savana/26.webp",
    title: "Sweetheart Neck Ruffle Cap Sleeve Maxi Dress in Baby Pink",
    description: "Step into timeless elegance with this stunning Sweetheart Neck Ruffle Cap Sleeve Maxi Dress in Baby Pink, designed to enhance your natural curves with a graceful silhouette. Crafted from a blend of polyester and lycra, it offers a soft feel with comfortable stretch for a flattering, sculpted fit. The sweetheart neckline adds a romantic touch, while the sleeveless design keeps the look sleek and refined. Finished with a mermaid hem, this dress flows beautifully for a dramatic and elegant finish. The baby pink shade brings a soft, feminine charm perfect for special occasions.Ideal for evening events, formal gatherings, or celebrations, this dress combines sophistication with modern allure..",
    productLink:"https://littleboxindia.com/products/sweetheart-neck-ruffle-cap-sleeve-maxi-dress-in-baby-pink?variant=52499130777887",
    },
     
    {
    id: 200,
    image: "/savana/27.webp",
    title: "Halter Neck Button Detail Maxi Dress in Baby Pink",
    description: "Halter Neck Button Detail Maxi Dress in Baby Pink is the perfect blend of timeless elegance and modern sophistication. Crafted from smooth woven fabric with a graceful drape, this halter neck button detail maxi dress features a chic halter neckline, a subtle front keyhole detail, and fabric-covered buttons that add a refined touch to the fitted bodice. The flowing A-line maxi silhouette flatters your figure while offering effortless movement, making this halter neck button detail maxi dress the perfect choice for weddings, cocktail parties, evening events, and formal celebrations..",
    productLink:"https://littleboxindia.com/products/halter-neck-button-detail-maxi-dress-in-baby-pink?variant=52666331529503",
    },
     {
    id: 201,
    image: "/savana/28.webp",
    title: "Bell Sleeve Tie Front Two Piece Set in Baby Pink",
    description: "Bell Sleeve Tie Front Two Piece Set in Baby Pink is a chic and feminine ensemble designed to bring effortless elegance and modern sophistication to your wardrobe. Featuring a coordinated two-piece design, this set creates a stylish and polished look perfect for brunches, vacations, parties, or elevated casual occasions..",
    productLink:"https://littleboxindia.com/products/bell-sleeve-tie-front-two-piece-set-in-baby-pink?variant=52582056755487",
    },
     {
    id: 202,
    image: "/savana/29.webp",
    title: "Boat Neckline Striped Bowknot Ruched Tank Top in Baby Pink",
    description: ".Introducing our Boat Neckline Striped Bowknot Ruched Tank Top in Baby PinkThis ruched tank top blends timeless pinstripes with cute side bows for a fresh take on summer layering. With a flattering boat neckline and a cinched hem, it delivers that snatched-on-top look without sacrificing comfort.Whether you're dressing for a laid-back hangout or something more elevated, this ruched tank top is your go-to for a cool-girl fit with zero effort.",
    productLink:"https://littleboxindia.com/products/boat-neckline-striped-bowknot-ruched-tank-top-in-baby-pink?variant=52581894095135",
    },
     {
    id: 203,
    image: "/savana/30.webp",
    title: "Slim Fit Button Down Top with Flared Sleeves in Baby Pink",
    description: "Introducing our Slim Fit Button Down Top with Flared Sleeves in Baby Pink. This flared sleeves top brings soft charm with a fitted silhouette and delicate texture. Designed with a collared neckline and button-down front, it’s a refined take on your everyday style with sleeves that make a statement..",
    productLink:"https://littleboxindia.com/products/ribbed-slim-fit-button-down-top-with-flared-sleeves-in-baby-pink?variant=51053944668447",
    },
     {
    id: 204,
    image: "/savana/31.webp",
    title: "Textured Knit Boxy Fit Top in Baby Pink",
    description: "The Textured Knit Boxy Fit Top in Baby Pink brings comfort and polish together in the easiest way. With its relaxed silhouette and soft textured fabric, this textured top is perfect for days you want to look put-together without trying too hard. The subtle sheen and delicate knit add a refined touch that works beautifully for both casual and semi-dressy plans.Made with a blend of polyester and lycra, it offers just the right amount of stretch for a flattering fit while staying breathable. This textured top pairs effortlessly with wide-leg trousers, skirts, or even denim for an instant chic update..",
    productLink:"https://littleboxindia.com/products/textured-knit-boxy-fit-top-in-baby-pink?variant=51072652214559",
    },
     {
    id: 205,
    image: "/savana/32.webp",
    title: "Pastel Blue Lounge Set Mirror Selfie | Cozy Apartment Outfit Inspiration",
    description: "Soft pastel blue lounge set styled with clean white sneakers and a canvas tote for a fresh, minimal everyday look. Captured in a bright, cozy apartment mirror selfie with warm natural lighting, this outfit is perfect for casual days, travel, coffee runs, and Pinterest fashion inspiration.",
    productLink:"https://www.savana.com/details/pullover-t-shirt-2300332?vid=19&skcPGs=376001-481391",
    },
     
     {
    id: 207,
    image: "/savana/33.webp",
    title: "Pink Draped Top & Denim Shorts | Chic Casual Summer Outfit Inspiration",
    description: "Effortlessly stylish and perfect for warm days, this outfit features a soft pink draped-neck fitted top paired with classic denim shorts, white sneakers, and a canvas tote bag. Finished with minimal jewellery and a refreshing iced drink, this cozy apartment mirror selfie captures a clean, feminine, and modern aesthetic. Whether you're heading to a coffee date, shopping, travelling, or enjoying a casual day out, this look offers the perfect balance of comfort and elegance for everyday fashion inspiration. 🌸✨.",
    productLink:"",
    },
     {
    id: 208,
    image: "/savana/34.webp",
    title: "Oversized Black Graphic Tee & Denim Mini Skirt | Casual Street Style Outfit Inspiration",
    description: "Create an effortlessly cool everyday look with this oversized black graphic T-shirt paired with a trendy denim mini skirt. Finished with chunky white sneakers, a stylish shoulder bag, and minimal accessories, this cozy apartment mirror selfie captures the perfect blend of comfort and street fashion. A versatile outfit for casual outings, shopping, coffee dates, weekend adventures, and Pinterest fashion inspiration..",
    productLink:"https://www.savana.com/details/contrast-pullover-t-shirt-2276072?vid=128&skcPGs=372565-475326",
    },
     {
    id: 209,
    image: "/savana/35.webp",
    title: "Sunny Yellow Top & White Wide-Leg Pants | Fresh Casual Outfit Inspiration",
    description: "Brighten up your everyday wardrobe with this fresh and effortless outfit featuring a soft yellow top layered over a grey inner tee, paired with relaxed white wide-leg pants and classic white sneakers. Finished with a canvas tote bag and minimal accessories, this cozy apartment mirror selfie captures a clean, modern aesthetic that's perfect for coffee dates, weekend outings, travel, and everyday wear. A simple yet stylish look for anyone who loves comfortable minimalist fashion and Pinterest-inspired outfits. ✨.",
    productLink:"",
    },
     {
    id: 210,
    image: "/savana/36.webp",
    title: "Classic Striped Shirt & Wide-Leg Jeans | Elegant Casual Outfit Inspiration",
    description: "Timeless and effortlessly chic, this outfit features a striped button-up shirt layered with a matching sweater draped over the shoulders for a sophisticated, preppy look. Paired with relaxed wide-leg blue jeans, white sneakers, and a canvas tote bag, it blends comfort with modern elegance. Captured in a cozy apartment mirror selfie, this versatile outfit is perfect for university, work, coffee dates, weekend outings, travel, and anyone who loves clean, minimalist fashion with a touch of classic style. ✨.",
    productLink:"",
    },
     {
    id: 211,
    image: "/savana/37.webp",
    title: "Pastel Blue Co-Ord Set Mirror Selfie | Minimal Casual Outfit Inspiration",
    description: "Elevate your everyday style with this pastel blue co-ord set featuring a zip-up top and wide-leg trousers. Styled with white sneakers and a canvas tote, this cozy apartment mirror selfie captures a clean, modern aesthetic that's perfect for casual outings, travel days, coffee dates, and effortless Pinterest fashion inspiration. ✨.",
    productLink:"https://www.savana.com/details/lace-trimmed-co-ord-set-2244662?vid=86&skcPGs=368260-470873",
    },
     
     











    

    
    
    
    




      
      

    
   


 
  

  
];

export default dataInfo;